--CONSULTAS DIVERSAS
--SELECT
--* SERVE PARA TRAZER TODOS OS CAMPOS
SELECT * FROM T_DEPARTAMENTO;
--CLAUSULA ORDER BY QUE NOS AJUDA A ORDENAR
SELECT * FROM T_DEPARTAMENTO ORDER BY CD_DEPARTAMENTO;
SELECT * FROM T_DEPARTAMENTO ORDER BY NM_DEPARTAMENTO;

SELECT NM_DEPARTAMENTO, SG_DEPARTAMENTO FROM T_DEPARTAMENTO ORDER BY NM_DEPARTAMENTO;
-- ORDENA DECRESCENTE
SELECT NM_DEPARTAMENTO, SG_DEPARTAMENTO FROM T_DEPARTAMENTO ORDER BY NM_DEPARTAMENTO DESC;
-- ORDENA SIGLA
-----------1 ------------- 2
SELECT NM_DEPARTAMENTO, SG_DEPARTAMENTO FROM T_DEPARTAMENTO ORDER BY 2; 

SELECT SG_DEPARTAMENTO || '-' || NM_DEPARTAMENTO FROM T_DEPARTAMENTO;
SELECT SG_DEPARTAMENTO || '-' || UPPER(NM_DEPARTAMENTO) AS DEPTO FROM T_DEPARTAMENTO;
SELECT SG_DEPARTAMENTO || '-' || 'A MELHOR TURMA' AS BRINCADEIRA FROM T_DEPARTAMENTO;

-- EXERCICIO TRAZER O NOME DO FUNCIONARIO:VALOR DO SALARIO
SELECT NM_FUNCIONARIO || ':R$' || VL_SALARIO_ATUAL FROM T_FUNCIONARIO ORDER BY NM_FUNCIONARIO;

SELECT TRIM(SG_DEPARTAMENTO) || '-' || UPPER(NM_DEPARTAMENTO) AS DEPTO FROM T_DEPARTAMENTO;

SELECT 
NR_MATRICULA, NM_FUNCIONARIO, 
VL_SALARIO_ATUAL, VL_SALARIO_ATUAL * 1.5 AS VL_SALARIO_AUMENTO
FROM T_FUNCIONARIO;

SELECT
NR_MATRICULA AS "Numero de Matricula",
NM_FUNCIONARIO AS "Nome do Funcionario",
TO_CHAR(DT_NASCIMENTO_FUNCIONARIO, 'YYYYMMDD') AS "Data de Nascimento"
FROM T_FUNCIONARIO;

--O DISTINCT GARANTE QUE NAO HÁ REPETIDOS
SELECT DISTINCT DT_NASCIMENTO_FUNCIONARIO
FROM T_FUNCIONARIO;

--CLAUSULA WHERE É O FILTRO DO NOSSO SELECT
SELECT * FROM T_FUNCIONARIO;
-- O FILTRO PODE COMBINAR COM OUTRO FILTRO USANDO O AND
-- A DATA SEMPRE TEM O HORARIO JUNTO, POR ISSO PODEMOS USAR 
-- O TRUNC (CORTAR, TRUNCAR) E RETIRA A PARTE DA HORA
SELECT NM_FUNCIONARIO FROM T_FUNCIONARIO 
WHERE VL_SALARIO_ATUAL > 5000 
AND TRUNC(DT_ADMISSAO) = '08/10/2024';

--TRAZER OS FUNCIONARIOS CUJA DATA DE NASCIMENTO SEJA MAIOR QUE 01/01/1980 e MENOR QUE 31/12/1990
SELECT NM_FUNCIONARIO FROM T_FUNCIONARIO
WHERE DT_NASCIMENTO_FUNCIONARIO >= TO_DATE('01/01/1980', 'DD/MM/YYYY') AND
DT_NASCIMENTO_FUNCIONARIO <= TO_DATE('31/12/1990', 'DD/MM/YYYY');

SELECT NM_FUNCIONARIO FROM T_FUNCIONARIO
WHERE DT_NASCIMENTO_FUNCIONARIO BETWEEN TO_DATE('01/01/1980', 'DD/MM/YYYY') AND
TO_DATE('31/12/1990', 'DD/MM/YYYY');

--OPERADOR LIKE
SELECT * FROM T_FUNCIONARIO WHERE UPPER(NM_FUNCIONARIO) LIKE 'A%';

--OPERADOR OR
SELECT * FROM T_FUNCIONARIO WHERE CD_DEPARTAMENTO = '1' OR CD_DEPARTAMENTO = '2';
--PODEMOS USAR O IN
SELECT * FROM T_FUNCIONARIO WHERE CD_DEPARTAMENTO IN ('1', '2');

--SUBSTRING PEGA UM PEDACO DOS DADOS
SELECT LOWER(SUBSTR(NM_FUNCIONARIO, 1, 4)) NM_FUNCIONARIO FROM T_FUNCIONARIO;

--ROWNUN: COLUNA ESCONDIDA DO ORACLE
SELECT ROWNUM, NM_FUNCIONARIO FROM T_FUNCIONARIO;
--TOP 10 FUNCIONARIOS
SELECT ROWNUM, NM_FUNCIONARIO FROM T_FUNCIONARIO WHERE ROWNUM <= 10;

SELECT NM_FUNCIONARIO
FROM T_FUNCIONARIO
WHERE LOWER(NM_FUNCIONARIO) LIKE '%de jesus' AND VL_SALARIO_ATUAL > 1300;
