-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-10-02 15:07:05 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE t_departamento CASCADE CONSTRAINTS;

DROP TABLE t_dependente CASCADE CONSTRAINTS;

DROP TABLE t_funcionario CASCADE CONSTRAINTS;

DROP TABLE t_implantacao CASCADE CONSTRAINTS;

DROP TABLE t_projeto CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE t_departamento (
    cd_departamento CHAR(2) NOT NULL,
    nm_departamento VARCHAR2(30) NOT NULL,
    sg_departamento CHAR(3)
);

COMMENT ON TABLE t_departamento IS
    'Departamento: São divisões de uma empresa, onde cada divisão tem um propósito. Precisamos do código numérico, nome do departamento e uma sigla com três letras para facilitar a identificação do departamento em relatórios.'
    ;

COMMENT ON COLUMN t_departamento.cd_departamento IS
    'Codigo do departamento';

COMMENT ON COLUMN t_departamento.nm_departamento IS
    'Nome do departamento';

COMMENT ON COLUMN t_departamento.sg_departamento IS
    'Sigla do Departamento';

ALTER TABLE t_departamento ADD CONSTRAINT t_departamento_pk PRIMARY KEY ( cd_departamento );

ALTER TABLE t_departamento ADD CONSTRAINT t_departamento__un UNIQUE ( nm_departamento );

CREATE TABLE t_dependente (
    nr_matricula             NUMBER(10) NOT NULL,
    cd_dependente            NUMBER(2) NOT NULL,
    nm_dependente            VARCHAR2(60) NOT NULL,
    dt_nascimento_dependente DATE NOT NULL,
    ds_grau_parentesco       VARCHAR2(15) NOT NULL
);

COMMENT ON TABLE t_dependente IS
    'Dependente: São pessoas que possuem um grau de parentesco com o funcionário, por exemplo: filhos, esposa ou marido. Neste primeiro momento precisamos do nome e data de nascimento de cada dependente do funcionário.'
    ;

COMMENT ON COLUMN t_dependente.cd_dependente IS
    'Codigo do dependente';

COMMENT ON COLUMN t_dependente.nm_dependente IS
    'Nome do dependente ';

COMMENT ON COLUMN t_dependente.dt_nascimento_dependente IS
    'Data de nascimento do dependente';

COMMENT ON COLUMN t_dependente.ds_grau_parentesco IS
    'Grau de parentesco do funcionario com o dependente (filho, enteado, pai, mãe, etc)';

ALTER TABLE t_dependente ADD CONSTRAINT t_dependente_pk PRIMARY KEY ( cd_dependente,
                                                                      nr_matricula );

CREATE TABLE t_funcionario (
    nr_matricula              NUMBER(10) NOT NULL,
    cd_departamento           CHAR(2) NOT NULL,
    nm_funcionario            VARCHAR2(60) NOT NULL,
    dt_nascimento_funcionario DATE NOT NULL,
    dt_admissao               DATE NOT NULL,
    vl_salario_atual          NUMBER(15, 2) NOT NULL,
    ds_endereco               VARCHAR2(100) NOT NULL
);

COMMENT ON TABLE t_funcionario IS
    'Funcionário: É uma pessoa que tem um skill, para desenvolver as tarefas as quais foi contratado. Precisamos do número da matrícula, nome completo do funcionário, data de nascimento, data da admissão, endereço completo e o salário mensal.'
    ;

COMMENT ON COLUMN t_funcionario.nr_matricula IS
    'Numero de matricula do funcionario';

COMMENT ON COLUMN t_funcionario.nm_funcionario IS
    'Nome do funcionario';

COMMENT ON COLUMN t_funcionario.dt_nascimento_funcionario IS
    'Data de nascimento do funcionario';

COMMENT ON COLUMN t_funcionario.dt_admissao IS
    'Data de admissão do funcionario';

COMMENT ON COLUMN t_funcionario.vl_salario_atual IS
    'Valor do salario do funcionario';

COMMENT ON COLUMN t_funcionario.ds_endereco IS
    'Endereco de residencia do funcionario';

ALTER TABLE t_funcionario ADD CONSTRAINT t_funcionario_pk PRIMARY KEY ( nr_matricula );

CREATE TABLE t_implantacao (
    cd_implantacao         NUMBER(10) NOT NULL,
    cd_projeto             NUMBER(10) NOT NULL,
    nr_matricula           NUMBER(10) NOT NULL,
    dt_entrada_funcionario DATE NOT NULL,
    dt_saida_funcionario   DATE
);

COMMENT ON TABLE t_implantacao IS
    'Implantação: Refere-se aos projetos desenvolvidos ou que estão em desenvolvimento, bem como os funcionários que estão desempenhando tarefas nestes projetos e em qual período. Precisamos de um código para a implantação numérico, o projeto e o funcionário que participa deste projeto e o período (entrada/saída) em que o funcionário atuou no projeto.'
    ;

COMMENT ON COLUMN t_implantacao.cd_implantacao IS
    'Codigo de implantacao';

COMMENT ON COLUMN t_implantacao.dt_entrada_funcionario IS
    'Data de entrada do funcionario do projeto';

COMMENT ON COLUMN t_implantacao.dt_saida_funcionario IS
    'Data de saida do funcionario (quando houver)';

ALTER TABLE t_implantacao ADD CONSTRAINT t_implantacao_pk PRIMARY KEY ( cd_implantacao );

CREATE TABLE t_projeto (
    cd_projeto         NUMBER(10) NOT NULL,
    nm_projeto         VARCHAR2(30) NOT NULL,
    dt_inicio_projeto  DATE NOT NULL,
    dt_termino_projeto DATE
);

COMMENT ON TABLE t_projeto IS
    'Projeto: Somos uma empresa que desenvolvemos soluções de TI. Desenvolvemos projetos para todas as áreas da TI. Precisamos do código do projeto numérico, nome ou título do projeto, a data em que o projeto foi iniciado e a data em que o projeto foi finalizado.'
    ;

COMMENT ON COLUMN t_projeto.cd_projeto IS
    'Codigo do projeto gerado automaticament';

COMMENT ON COLUMN t_projeto.nm_projeto IS
    'Nome do projeto';

COMMENT ON COLUMN t_projeto.dt_inicio_projeto IS
    'Data de inicio do projeto';

COMMENT ON COLUMN t_projeto.dt_termino_projeto IS
    'Data de termino do projeto (quando houver)';

ALTER TABLE t_projeto ADD CONSTRAINT t_projeto_ck_dt_termino CHECK ( dt_termino_projeto >= dt_inicio_projeto );

ALTER TABLE t_projeto ADD CONSTRAINT t_projeto_pk PRIMARY KEY ( cd_projeto );

ALTER TABLE t_funcionario
    ADD CONSTRAINT fk_depto_func FOREIGN KEY ( cd_departamento )
        REFERENCES t_departamento ( cd_departamento );

ALTER TABLE t_dependente
    ADD CONSTRAINT fk_func_dependente FOREIGN KEY ( nr_matricula )
        REFERENCES t_funcionario ( nr_matricula );

ALTER TABLE t_implantacao
    ADD CONSTRAINT fk_func_implantacao FOREIGN KEY ( nr_matricula )
        REFERENCES t_funcionario ( nr_matricula );

ALTER TABLE t_implantacao
    ADD CONSTRAINT fk_projeto_implantacao FOREIGN KEY ( cd_projeto )
        REFERENCES t_projeto ( cd_projeto );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
