-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-10-03 15:02:22 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE t_cli_alergia CASCADE CONSTRAINTS;

DROP TABLE t_cli_consulta CASCADE CONSTRAINTS;

DROP TABLE t_cli_especialidade CASCADE CONSTRAINTS;

DROP TABLE t_cli_medico CASCADE CONSTRAINTS;

DROP TABLE t_cli_paciente CASCADE CONSTRAINTS;

DROP TABLE t_paciente_alergia CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE t_cli_alergia (
    id_alergia NUMBER(10) NOT NULL,
    ds_alergia VARCHAR2(100) NOT NULL,
    tp_alergia VARCHAR2(15) NOT NULL
);

COMMENT ON TABLE t_cli_alergia IS
    'Alergia: São condições de pacientes que podem ocorrer. Devemos armazenar o tipo de alergia (medicamentosa, alimentar, dermatologica) e a descricao da alergia

';

COMMENT ON COLUMN t_cli_alergia.id_alergia IS
    'Numero gerado artificialmente para ser primary key da alergia';

COMMENT ON COLUMN t_cli_alergia.ds_alergia IS
    'Descricao da alergia';

COMMENT ON COLUMN t_cli_alergia.tp_alergia IS
    'Tipo da alergia: medicamentosa, de pele, alimento';

ALTER TABLE t_cli_alergia ADD CONSTRAINT t_cli_alergia_pk PRIMARY KEY ( id_alergia );

CREATE TABLE t_cli_consulta (
    id_consulta     NUMBER(10) NOT NULL,
    cd_crm          CHAR(12) NOT NULL,
    nr_cpf_paciente NUMBER(11) NOT NULL,
    dt_hr_consulta  DATE NOT NULL,
    vl_consulta     NUMBER(10, 2) NOT NULL
);

COMMENT ON TABLE t_cli_consulta IS
    'Consulta: é um agendamento que ocorre para que o paciente e o médico se encontrem



';

COMMENT ON COLUMN t_cli_consulta.id_consulta IS
    'Identifcador gerado artificialmente para identificar uma consulta';

COMMENT ON COLUMN t_cli_consulta.dt_hr_consulta IS
    'Data e hora da consulta';

COMMENT ON COLUMN t_cli_consulta.vl_consulta IS
    'Valor pago pela consulta';

ALTER TABLE t_cli_consulta ADD CONSTRAINT t_cli_consulta_pk PRIMARY KEY ( cd_crm,
                                                                          id_consulta );

CREATE TABLE t_cli_especialidade (
    cd_especialidade CHAR(3) NOT NULL,
    nm_especialidade VARCHAR2(30) NOT NULL
);

COMMENT ON TABLE t_cli_especialidade IS
    'Especialidade: É o curso que profissionaliza o médico em uma determinada área. Precisamos no código da especialidade, do nome da especialidade.

';

COMMENT ON COLUMN t_cli_especialidade.cd_especialidade IS
    'Codigo da especialidade';

COMMENT ON COLUMN t_cli_especialidade.nm_especialidade IS
    'Nome da especialidade';

ALTER TABLE t_cli_especialidade ADD CONSTRAINT t_cli_especialidade_pk PRIMARY KEY ( cd_especialidade );

CREATE TABLE t_cli_medico (
    cd_crm             CHAR(12) NOT NULL,
    cd_especialidade   CHAR(3) NOT NULL,
    nm_medico          VARCHAR2(60) NOT NULL,
    ds_endereco_medico VARCHAR2(100) NOT NULL,
    nr_telefone_medico NUMBER(11) NOT NULL,
    vl_salario         NUMBER(10, 2) NOT NULL
);

COMMENT ON TABLE t_cli_medico IS
    'Médicos: São profissionais formados da área de sáude que atendem os pacientes.. Precisamos do CRM do médico, nome, endereço, telefone, especialidade, valor de salario.



';

COMMENT ON COLUMN t_cli_medico.cd_crm IS
    'Codigo do CRM do MEDICO no formato CRMnnnnnn/ES (ESTADO: SP, RJ, MS)';

COMMENT ON COLUMN t_cli_medico.nm_medico IS
    'Nome do medico';

COMMENT ON COLUMN t_cli_medico.ds_endereco_medico IS
    'Endereco do Medico';

COMMENT ON COLUMN t_cli_medico.nr_telefone_medico IS
    'Numero do telefone do medico';

COMMENT ON COLUMN t_cli_medico.vl_salario IS
    'Valor atual do salario do medico';

ALTER TABLE t_cli_medico ADD CONSTRAINT t_cli_medico_pk PRIMARY KEY ( cd_crm );

CREATE TABLE t_cli_paciente (
    nr_cpf_paciente      NUMBER(11) NOT NULL,
    nm_paciente          VARCHAR2(60) NOT NULL,
    dt_nasc_paciente     DATE NOT NULL,
    ds_endereco_paciente VARCHAR2(100) NOT NULL,
    nr_tel_paciente      NUMBER(11) NOT NULL,
    nr_carteira_convenio NUMBER(18)
);

COMMENT ON TABLE t_cli_paciente IS
    'Pacientes: São pessoas procuram a clinica com alguma queixa. Nesse momento precisamos do nome completo, CPF, data de nascimento, endereço completo, telefone de contato, numero da carteira de convencio se ele possuir



';

COMMENT ON COLUMN t_cli_paciente.nr_cpf_paciente IS
    'CPF do paciente';

COMMENT ON COLUMN t_cli_paciente.nm_paciente IS
    'Nome do paciente';

COMMENT ON COLUMN t_cli_paciente.dt_nasc_paciente IS
    'Data de nascimento do paciente';

COMMENT ON COLUMN t_cli_paciente.ds_endereco_paciente IS
    'Endereco do paciente';

COMMENT ON COLUMN t_cli_paciente.nr_tel_paciente IS
    'Telefone do paciente com DDD';

COMMENT ON COLUMN t_cli_paciente.nr_carteira_convenio IS
    'Numero da carteira do Convenio';

ALTER TABLE t_cli_paciente ADD CONSTRAINT t_cli_paciente_pk PRIMARY KEY ( nr_cpf_paciente );

CREATE TABLE t_paciente_alergia (
    nr_cpf_paciente NUMBER(11) NOT NULL,
    id_alergia      NUMBER(10) NOT NULL
);

COMMENT ON TABLE t_paciente_alergia IS
    'É a relacao entre paciente e alergia
Um paciente pode ter 0 ou muitas alergias. 
Uma alergia pode estar associada a 0 ou muitos pacientes';

ALTER TABLE t_paciente_alergia ADD CONSTRAINT t_paciente_alergia_pk PRIMARY KEY ( nr_cpf_paciente,
                                                                                  id_alergia );

ALTER TABLE t_paciente_alergia
    ADD CONSTRAINT fk_alergia_pac_alergia FOREIGN KEY ( id_alergia )
        REFERENCES t_cli_alergia ( id_alergia );

ALTER TABLE t_cli_medico
    ADD CONSTRAINT fk_espec_medico FOREIGN KEY ( cd_especialidade )
        REFERENCES t_cli_especialidade ( cd_especialidade );

ALTER TABLE t_cli_consulta
    ADD CONSTRAINT fk_medico_consulta FOREIGN KEY ( cd_crm )
        REFERENCES t_cli_medico ( cd_crm );

ALTER TABLE t_paciente_alergia
    ADD CONSTRAINT fk_pac_pac_alergia FOREIGN KEY ( nr_cpf_paciente )
        REFERENCES t_cli_paciente ( nr_cpf_paciente );

ALTER TABLE t_cli_consulta
    ADD CONSTRAINT fk_paciente_consulta FOREIGN KEY ( nr_cpf_paciente )
        REFERENCES t_cli_paciente ( nr_cpf_paciente );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
