--COMANDOS DE CRIACAO, ALTERACAO E EXCLUSAO DE OBJETO

-- COMO CRIAR UMA TABELA NA MAO
CREATE TABLE T_TESTE_DDL
(
    id_teste NUMBER (10) NOT NULL, --criando um campo numerico de tamanho 10 obrigatorio
    nm_teste VARCHAR2(15) NOT NULL, --criando um campo texto de tamanho 15 obrigatorio
    ds_teste VARCHAR2(100) NULL --criando um campo texto de tamanho 100 opcional
);

--COMO EXCLUIR UMA TABELA NA MAO
DROP TABLE T_TESTE_DDL; --estamos apagando a tabela
DROP TABLE T_TESTE_DDL CASCADE CONSTRAINTS; --estamos apagando a tabela e também os relacionamentos
DROP TABLE T_TESTE_DDL CASCADE CONSTRAINTS PURGE; --estamos apagando a tabela e também os relacionamentos 
-- O COMANDO PURGE É PARA ESVAZIAR A LIXEIRA, OU SEJA, 
--quando estamos apagando o objeto dessa maneira NAO TEMOS A POSSIBILIDADE DE VOLTAR ATRÁS

--COMO ALTERAR TABELA
--NOME DA TABELA
ALTER TABLE T_TESTE_DDL RENAME TO T_TESTE_DDL_2024;
ALTER TABLE T_TESTE_DDL_2024 RENAME TO T_TESTE_DDL;
--CRIAR CHAVE PRIMARIA
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT PK_TESTE_DDL PRIMARY KEY (id_teste);
--CRIAR REGRA (CONSTRAINT)DE NOME QUE NAO REPETE
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_DDL_NOME UNIQUE (nm_teste);
--ADICIONAR UMA COLUNA
ALTER TABLE T_TESTE_DDL ADD DS_EMAIL VARCHAR2(100);
--ADICIONAR DUAS COLUNAS
ALTER TABLE T_TESTE_DDL ADD (DS_OBS1 VARCHAR2(100) NOT NULL, DS_OBS2 VARCHAR(100));

--CONSULTANDO A ESTRUTURA DE UMA TABELA
DESC T_TESTE_DDL;
-- EXISTEM TABELAS INTERNAS DO ORACLE QUE TEM AS ESTRUTURAS DAS TABELAS
-- SAO TABELAS DE TABELAS (USER_TABLES)
-- NESSAS TABELAS CONSEGUIMOS VER TUDO REFERENTE A UMA TABELA
-- POR EXEMPLO SEUS ATRIBUTOS FISICOS E SE ELA TEM CONSTRAINTS
SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'T_TESTE_DDL';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'T_TESTE_DDL';
-- É NA TABELA USER_CONS_COLUMNS QUE VEMOS SE TEM PRIMARY KEY
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'T_TESTE_DDL';

DESC USER_TABLES
DESCRIBE T_TESTE_DDL;

-- MODIFICAR ESPECIFICACOES DE UM CAMPO NA TABELA
ALTER TABLE T_TESTE_DDL MODIFY DS_OBS2 VARCHAR2(50) NOT NULL;

-- ADICIONANDO UM CAMPO DATA NA TABELA
ALTER TABLE T_TESTE_DDL ADD DT_TESTE_DDL DATE DEFAULT SYSDATE;

DESC T_TESTE_DDL

--RENOMEANDO CAMPOS 
ALTER TABLE T_TESTE_DDL RENAME COLUMN DS_OBS1 TO DS_OBS3;

--ACRESCENTANDO COMENTARIOS
COMMENT ON TABLE T_TESTE_DDL IS 'Teste de tabela para comandos de estrutura DDL';

--REMOVENDO CAMPOS
ALTER TABLE T_TESTE_DDL DROP COLUMN DS_OBS2;
ALTER TABLE T_TESTE_DDL DROP (DS_OBS3, DT_TESTE_DDL);

DESC T_TESTE_DDL

DROP TABLE T_TESTE_DDL
CREATE TABLE T_TESTE_DDL
(
    id_teste NUMBER (10) NOT NULL, --criando um campo numerico de tamanho 10 obrigatorio
    nm_teste VARCHAR2(30) NOT NULL, --criando um campo texto de tamanho 15 obrigatorio
    ds_teste VARCHAR2(100) NULL, --criando um campo texto de tamanho 100 opcional
    ds_email VARCHAR2(100) NULL 
);

-- POPULAR DADOS
-- O COMANDO INSERT INSERE DADOS NA TABELA
INSERT INTO T_TESTE_DDL (
    id_teste,
    nm_teste,
    ds_teste,
    ds_email
)
VALUES (
    1,
    'TESTE NUMERO 1',
    'DESCRITIVO DE TESTE 1',
    'EMAIL DE TESTE 1'
);

-- CONSULTA 
SELECT * FROM T_TESTE_DDL;
-- CONFIRMACAO
COMMIT;

--OS CAMPOS DS_TESTE e DS_EMAIL nao sao obrigatorios
-- se eu quisesse inserir mais um registro 
--com os dados 'Teste 2' e  como eu deveria fazer?
INSERT INTO T_TESTE_DDL (
    id_teste,
    nm_teste
)
VALUES (
    2,
    'TESTE NUMERO 2'
);
COMMIT;
SELECT * FROM T_TESTE_DDL;

INSERT INTO T_TESTE_DDL (
    id_teste,
    nm_teste,
    ds_teste,
    ds_email
)
VALUES (
    3,
    'TESTE NUMERO 3',
    '',
    ''
);
COMMIT;
SELECT * FROM T_TESTE_DDL;

INSERT INTO T_TESTE_DDL (
    id_teste,
    nm_teste,
    ds_teste,
    ds_email
)
VALUES (
    4,
    'TESTE NUMERO 4',
    NULL,
    NULL
);
COMMIT;
SELECT * FROM T_TESTE_DDL;


